name: profile_photo
description: A simple Flutter package to display a profile photo with a badge
version: 1.0.0
homepage: https://github.com/bradv123/profile_photo

environment:
  sdk: ">=2.16.2 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter